name: camilla
description: sitemap.xml generator for a static website
version: 1.0.1
homepage: https://github.com/sasuw/camilla

environment:
  sdk: '>=2.12.0'

dependencies:
  xml: ^6.5.0
  intl: any

dev_dependencies:
  test: ^1.14.4
  lints: ^5.1.1
